### ISSUE TITLE
Run celery in factory example

### ISSUE THREAD

**Issue by hamidfzm** [Robpol86/Flask-Celery-Helper#12]
I'm trying to run celery using factory example structure:

```python
# config.py
class DefaultConfig(object):
    CELERY_BROKER_URL = 'redis://localhost:6379/5'
    CELERY_RESULT_BACKEND = 'redis://localhost:6379/5'
    CELERY_IMPORTS = (
        'tasks.send_mail',
    )
    # some other config ...
```

```python
# extensions.py

# python imports
from py2neo import Graph
from elasticsearch import Elasticsearch
from redis import StrictRedis

# flask imports
from flask_wtf import CsrfProtect
from flask.ext.babel import Babel
from flask.ext.mongoengine import MongoEngine
from flask.ext.htmlmin import HTMLMIN
from flask.ext.mail import Mail
from flask.ext.celery import Celery

# project imports
from application.modules.sms import SMS
# from application.modules.email import MandrillEmail
from config import DefaultConfig

__all__ = ['db', 'babel', 'graph', 'htmlmin', 'es', 'csrf', 'redis', 'email', 'sms', 'celery']


babel = Babel()
db = MongoEngine()
graph = Graph(DefaultConfig.NEO4J_URI)
htmlmin = HTMLMIN()
es = Elasticsearch(DefaultConfig.ES_HOST)
csrf = CsrfProtect()
sms = SMS()
redis = StrictRedis()
# email = MandrillEmail()
email = Mail()
celery = Celery()
```

```python
# application.py
# python imports
import os
import time

# flask imports
from flask import Flask, session, g, request, render_template

# project imports
from config import DefaultConfig

def configure_app(app, configuration):
    app.config.from_object(DefaultConfig)

    if configuration is not None:
        app.config.from_object(configuration)

def configure_blueprints(app):
    # register blueprint ...
    pass

def configure_extensions(app):
    import application.extensions as ex

    for extension in ex.__all__:
        try:
            getattr(ex, extension).init_app(app)
        except AttributeError:
            pass


def create_app(configuration):
    app = Flask(__name__)

    configure_app(app, configuration)
    configure_extensions(app)
    configure_blueprints(app)

    return app
```

```python
# tasks.py

# project imports
from application.extensions import celery, email


@celery.task()
def send_mail(msg):
    email.send(msg)
```

```python
# develop.py
#!/usr/bin/env python

__author__ = 'Hamid FzM'

from application import create_app
from application.config import DeploymentConfig

app = create_app(DeploymentConfig)

if __name__ == '__main__':
    app.run()
```

Until now everything works perfect. I can run flask app easily without problem but when I'm trying to run celery using this command:
 `$ celery -A extensions.celery worker`

I always get some kind of import problem like this one:
```
Traceback (most recent call last):
  File "/var/www/inpacket/venv/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/var/www/inpacket/venv/local/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/var/www/inpacket/venv/local/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/var/www/inpacket/venv/local/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/var/www/inpacket/venv/local/lib/python2.7/site-packages/celery/bin/base.py", line 309, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/var/www/inpacket/venv/local/lib/python2.7/site-packages/celery/bin/base.py", line 469, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/var/www/inpacket/venv/local/lib/python2.7/site-packages/celery/bin/base.py", line 489, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/var/www/inpacket/venv/local/lib/python2.7/site-packages/celery/app/utils.py", line 229, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/var/www/inpacket/venv/local/lib/python2.7/site-packages/celery/bin/base.py", line 492, in symbol_by_name
    return symbol_by_name(name, imp=imp)
  File "/var/www/inpacket/venv/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 92, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/var/www/inpacket/venv/local/lib/python2.7/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/inpacket/application/extensions.py", line 10, in <module>
    from flask.ext.babel import Babel
  File "/var/www/inpacket/venv/local/lib/python2.7/site-packages/flask/exthook.py", line 81, in load_module
    reraise(exc_type, exc_value, tb.tb_next)
  File "/var/www/inpacket/venv/local/lib/python2.7/site-packages/flask_babel/__init__.py", line 21, in <module>
    from babel import dates, numbers, support, Locale
ImportError: cannot import name dates
```

I think there should be a context problem with this module unless I should run celery another way.

**Comment by Robpol86** [comment]
Wait I just looked at the traceback, and the exception is in Flask-Babel. If you remove `from flask.ext.babel import Babel` and `babel = Babel()` from `extensions.py` I bet everything will work.
